"""PostStore Protocol（spec §3.3）：Demo=SqliteStore，生产=MongoStore（motor），签名对齐。"""
from datetime import datetime
from typing import Protocol

import numpy as np

from app.domain import ErrorCode, PostRecord, SimilarityResult


class PostStore(Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def upsert_post(self, rec: PostRecord) -> bool: ...
    async def get_post(self, post_id: str) -> PostRecord | None: ...
    async def persist_vectors(self, post_id: str, image_vec: bytes, text_vec: bytes) -> None: ...
    async def mark_indexed(self, post_id: str, result: SimilarityResult) -> None: ...
    async def mark_failed(self, post_id: str, code: ErrorCode) -> None: ...
    async def get_result(self, post_id: str) -> SimilarityResult | None: ...
    async def list_stale_pending(self, older_than: datetime) -> list[str]: ...
    async def list_indexed_within(self, cutoff: datetime) -> list[tuple[str, bytes, bytes, datetime]]: ...
    async def reset_failed_to_pending(self, post_id: str) -> bool: ...
    async def counts(self) -> dict: ...
